### ISSUE TITLE
Yosemite support

### ISSUE THREAD

**Issue by DaveBlooman** [wallace/weechat-notification-center-rb#4]
I am using the same .weechat folder that I had on mavericks, install gems under system Ruby, 
![screenshot 2014-10-20 15 30 43](https://cloud.githubusercontent.com/assets/1492067/4702796/c75be13e-5865-11e4-8ffc-5125d7972a63.png)
Using Homebrew for install, but it doesn't seem to load the plugin at all.
 
![screenshot 2014-10-20 15 32 02](https://cloud.githubusercontent.com/assets/1492067/4702811/e4711096-5865-11e4-9037-ac8d56078ea0.png)

**Comment by wallace** [comment]
Hi @DaveBlooman,

This last weekend, I did a complete re-install using Yosemite. I found that I must now run command line application `weechat` via `sudo` to ensure that the weechat application has the proper access rights to access the `weechat` gem.

Otherwise, I get an error like the following:

![1__weechat_1_2__weechat_](https://cloud.githubusercontent.com/assets/11443/9583091/5a3e7598-4fd7-11e5-964c-c6ed9888f29f.png)

I'll update the README here shortly. Thanks for the error report.

**Comment by wallace** [comment]
Also, I found an issue with `curl` command too that required me to manually copy the raw file. I did not look into that further so I'd make sure that the curl command is properly populating the `.weechat/ruby/autoload/notification_center.rb` file.
